# Generated by Django 5.2.1 on 2025-05-18 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_discount_product_is_in_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gave_star',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
